### ISSUE TITLE
How do I run the program?

### ISSUE THREAD

**Issue by amirahar** [Dementophobia/string-art#1]
Hi
I don't know
How do I run the program?

**Comment by Dementophobia** [comment]
Hi,

it is currently a set of Python scripts that have to be called in sequence, with manual optimization (on code and configuration level) in between. It is not a tool you simply run, it is part of the creation process and evolves over time together with the artist. You can read more about this in [Human and AI collaboration](https://github.com/Dementophobia/string-art/blob/master/human_ai_collaboration.md#human-and-ai-collaboration).

Based on this personal connection, I decided not to publish the source code, so you cannot run it directly. But I have documented the algorithm in the article linked above, so everyone can develop their own version and personalize it to their needs.
